CREATE TABLE PRODUTO (
                         ID BIGINT NOT NULL AUTO_INCREMENT,
                         NOME VARCHAR(255) NOT NULL,
                         DESCRICAO VARCHAR(500),
                         CODIGO VARCHAR(100) NOT NULL UNIQUE,
                         PRECO DECIMAL(10,2) NOT NULL,
                         PRECO_PROMOCIONAL DECIMAL(10,2),
                         QUANTIDADE_ESTOQUE INT NOT NULL,
                         DATA_VALIDADE DATE,
                         DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                         CATEGORIA_ID BIGINT NULL,
                         FORNECEDOR_ID BIGINT NULL,

                         PRIMARY KEY (ID),
                         CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(ID),
                         CONSTRAINT FK_PRODUTO_FORNECEDOR FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDOR(ID)
) -- FECHOU O PARENTESES AQUI
    ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
